redis-ha:
  enabled: true

controller:
  enableStatefulSet: true

server:
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 3
  ingress:
    enabled: false

repoServer:
  autoscaling:
    enabled: true
    minReplicas: 2
